language: python

python:
  - "2.7"

env:
  - ANSIBLE_VERSION="ansible==2.2.3"
  - ANSIBLE_VERSION="ansible==2.3.1"
  - ANSIBLE_VERSION="git+https://github.com/ansible/ansible.git@devel"

install:
  - pip install pytest
  - pip install -q $ANSIBLE_VERSION

script:
  - ansible --version
  - py.test tests/